### ISSUE TITLE
Questionning the comparison with SSL methods on paperwithcode

### ISSUE THREAD

**Issue by mathildecaron31** [baaivision/EVA#23]
Hi,

Congrats on this interesting work.

I am wondering whether the comparisons with previous works [here](https://paperswithcode.com/sota/self-supervised-image-classification-on-1?p=eva-exploring-the-limits-of-masked-visual) and [here](https://paperswithcode.com/sota/self-supervised-image-classification-on?p=eva-exploring-the-limits-of-masked-visual) are really fair given that you are sort of distilling from CLIP encoders (i.e. which use text supervision).

**Comment by Yuxin-CV** [comment]
Hi @mathildecaron31, thanks for your interest in our work and your valuable question.

We believe using image-text paired data is a kind of self-supervised learning now, because now more and more images / videos naturally come with text / caption (I think it is easier to find an image w/ text than an image w/o text now). Image-text pairs are abundant on the Internet, and the data collocation process is scalable. So it is OK to say images are born with text now.

Notice that [here](https://paperswithcode.com/sota/self-supervised-image-classification-on-1?p=eva-exploring-the-limits-of-masked-visual) and [here](https://paperswithcode.com/sota/self-supervised-image-classification-on?p=eva-exploring-the-limits-of-masked-visual) are results from EVA-CLIP, so we not only ''distill from OpenAI CLIP encoders'', we also directly using LAION-400M image-text data for EVA-CLIP training.

**Comment by mathildecaron31** [comment]
Then maybe would be nice to add this somehow in the table so that it is clear to the reader that you are using text supervision (given that all the other entries in these pages don't use any text supervision).

**Comment by Yuxin-CV** [comment]
Good suggestion. The PwC badges have been modified as follows:

[![PWC](https://img.shields.io/endpoint.svg?url=https://paperswithcode.com/badge/eva-exploring-the-limits-of-masked-visual/self-supervised-image-classification-with-2)](https://paperswithcode.com/sota/self-supervised-image-classification-with-2?p=eva-exploring-the-limits-of-masked-visual) \
[![PWC](https://img.shields.io/endpoint.svg?url=https://paperswithcode.com/badge/eva-exploring-the-limits-of-masked-visual/self-supervised-image-classification-with-3)](https://paperswithcode.com/sota/self-supervised-image-classification-with-3?p=eva-exploring-the-limits-of-masked-visual) \
[![PWC](https://img.shields.io/endpoint.svg?url=https://paperswithcode.com/badge/eva-exploring-the-limits-of-masked-visual/self-supervised-image-classification-with)](https://paperswithcode.com/sota/self-supervised-image-classification-with?p=eva-exploring-the-limits-of-masked-visual)

**Comment by mathildecaron31** [comment]
Thanks a lot for your answer and congrats again on the work :)
