### ISSUE TITLE
inconsistence in the function `_jax_init`

### ISSUE THREAD

**Issue by chensnathan** [baaivision/EVA#44]
Hi, great work to EVA-02.

It seems that there exists an inconsistence in the function `_jax_init`. 

The code comment is [`we use xavier_uniform following official JAX ViT & MAE`](https://github.com/baaivision/EVA/blob/f9ca2c364a7aa5c628e6a966b07a75f73afa88d1/EVA-02/asuka/modeling_pretrain.py#L192), while using `xavier_normal_` instead in [L193](https://github.com/baaivision/EVA/blob/f9ca2c364a7aa5c628e6a966b07a75f73afa88d1/EVA-02/asuka/modeling_pretrain.py#L193).

It is intended or is a typo?

Thanks.

**Comment by Yuxin-CV** [comment]
Hi @chensnathan, thanks for your interest in EVA-02.

We call it "JAX init" because "we use xavier_uniform following official JAX ViT & MAE". Essentially we use `xavier_uniform` following the weight initialization in MAE(https://github.com/facebookresearch/mae/blob/efb2a8062c206524e35e47d04501ed4f544c0ae8/models_mae.py#L87) and JAX ViT(https://github.com/google-research/big_vision/blob/47ac2fd075fcb66cadc0e39bd959c78a6080070d/big_vision/models/vit.py#L65, https://github.com/google-research/big_vision/blob/47ac2fd075fcb66cadc0e39bd959c78a6080070d/big_vision/models/vit.py#L89).

We will clarify this and cite ``xavier_uniform`` init in the revision.

**Comment by chensnathan** [comment]
Yes, I know that MAE and JAX ViT use `xavier_uniform`.

But the code in [L193](https://github.com/baaivision/EVA/blob/f9ca2c364a7aa5c628e6a966b07a75f73afa88d1/EVA-02/asuka/modeling_pretrain.py#L193) is `xavier_normal_`.

So, from the response, this is a typo?

**Comment by Yuxin-CV** [comment]
Yes, we always use ``xavier_normal_`` in our experiment, and we never tried ``xavier_uniform``. 

We will fix the description in the revision, thanks for raising this issue.

**Comment by chensnathan** [comment]
Thanks for the explanation.
