### ISSUE TITLE
installation on colab

### ISSUE THREAD

**Issue by mohamedettebayo** [baaivision/EVA#7]
Please I am having issue installing EVA
can anyone please help me installing and configuring EVA on google colab notebook ?
if possible send me a colab notebook

**Comment by Yuxin-CV** [comment]
Hi @mohamedettebayo, sorry for the late reply.

I am not quite familiar with settings up projects on google colab notebooks, and each downstream task of EVA has different requirements / dependencies.

For example, if you are interested in the object detection / instance segmentation part of EVA, you can refer to [detectron2](https://github.com/facebookresearch/detectron2/issues?q=google+colab+notebook) for how to set up D2 projects on google colab notebooks, since EVA det is built upon D2 and D2 is quite popular in the detection communities. Maybe you can ask them for help?

**Comment by mohamedettebayo** [comment]
Thank you for your reply
I am grateful thanks 🙏

**Comment by Yuxin-CV** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.
