### ISSUE TITLE
Error during fine-tuning EVA object detector

### ISSUE THREAD

**Issue by CamielK** [baaivision/EVA#8]
Hello,

I am fine-tuning EVA on my custom dataset. I ran into the following error (it also happens when fine-tuning on COCO):
```
File "train.py", line 187, in <module>
  main(args)
File "train.py", line 169, in main
  trainer.train(0, cfg.train.max_iter)
File "/home/appuser/eva_repo/det/detectron2/engine/train_loop.py", line 149, in train
  self.run_step()
File "/home/appuser/eva_repo/det/detectron2/engine/train_loop.py", line 421, in run_step
  self.grad_scaler.scale(losses).backward()
File "/home/appuser/.local/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
  torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
File "/home/appuser/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
  allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
File "/home/appuser/.local/lib/python3.7/site-packages/torch/autograd/function.py", line 87, in apply
  return self._forward_cls.backward(self, *args)  # type: ignore[attr-defined]
File "/home/appuser/.local/lib/python3.7/site-packages/fairscale/nn/checkpoint/checkpoint_activations.py", line 331, in backward
  outputs = ctx.run_function(*unpacked_args, **unpacked_kwargs)
File "/home/appuser/eva_repo/det/detectron2/modeling/backbone/vit.py", line 289, in forward
  x = self.attn(x)
File "/home/appuser/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
  return forward_call(*input, **kwargs)
File "/home/appuser/eva_repo/det/detectron2/modeling/backbone/vit.py", line 139, in forward
  attn = add_decomposed_rel_pos(attn, q, self.rel_pos_h, self.rel_pos_w, (H, W), (H, W))
File "/home/appuser/eva_repo/det/detectron2/modeling/backbone/utils.py", line 133, in add_decomposed_rel_pos
  Rh = get_rel_pos(q_h, k_h, rel_pos_h)
File "/home/appuser/eva_repo/det/detectron2/modeling/backbone/utils.py", line 100, in get_rel_pos
  z = rel_pos[:, i].view(src_size).cpu().float().numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

The error is caused by this line:
https://github.com/baaivision/EVA/blob/098c493af0b31499ee2930beb09edcc38fac2974/det/detectron2/modeling/backbone/utils.py#L100

I fixed it by changing it to:
```python
z = rel_pos[:, i].view(src_size).cpu().float().detach().numpy()
```
After this change, the training runs without issue and the loss decreases steadily. 

But I am not sure if I understand the full implications of this change. 
Calling .detach() means the gradients are not updated for this Tensor. Or is that not an issue for this call? Did you not get this error during training?

I am running EVA inside docker with CUDA 11.1, Python 3.7, torch 1.9.0, torchvision 0.10.0, mmcv-full 1.6.1. But I doubt this is a versioning issue

**Comment by Yuxin-CV** [comment]
Hi @CamielK, thanks for trying EVA and reporting this issue.

The current rel pos interpolation implementation is from [BEiT](https://github.com/microsoft/unilm/blob/05eca1759a98d52f3f5c9de797c5be06ef45cdcd/beit/run_class_finetuning.py#L402), which we find can bring ~0.2 AP improvement if evaluated with a higher resolution (_e.g._, 1536px) than training / fine-tuning (_e.g._, 1280px) compared with the original rel pos interpolation implementation in [ViTDet](https://github.com/facebookresearch/detectron2/blob/96c752ce821a3340e27edd51c28a00665dd32a30/detectron2/modeling/backbone/utils.py#L77).

When we **training / fine-tuning** with a higher resolution, _e.g._, from 1024px on O365 to 1280px on COCO, we actually use the original rel pos interpolation implementation in [ViTDet](https://github.com/facebookresearch/detectron2/blob/96c752ce821a3340e27edd51c28a00665dd32a30/detectron2/modeling/backbone/utils.py#L77).

I think your hack (i.e., `z = rel_pos[:, i].view(src_size).cpu().float().detach().numpy()`) is also OK if you want to fine-tune at a higher resolution (because this implementation can bring improvement during evaluation even without fine-tuning). I also suggest you try the original implementation in [ViTDet](https://github.com/facebookresearch/detectron2/blob/96c752ce821a3340e27edd51c28a00665dd32a30/detectron2/modeling/backbone/utils.py#L77). But I think there is no much difference in terms of the performance.

Finally, all these implementations interpolate rel pos **on the fly for every forward / backward pass**, which I believe it is better to interpolate only once at the time one initializes the model. I will also work on this as long as I have time / GPUs.

**Comment by CamielK** [comment]
I checked out the latest commit and the training is much faster now. I have not done extensive tests but it appears to be almost twice as fast with the ViTDet implementation. I will defintely test the BEiT approach during final eval to compare AP performance

Thanks for the quick fix!
